INSERT INTO PRODUCTS (NAME) VALUES ('Computer')
INSERT INTO PRODUCTS (NAME) VALUES ('Car')

INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME) VALUES ('Victor', 'Nordstrand')
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME) VALUES ('Håkan', 'Nilsson')
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME) VALUES ('Hans', 'Jensen')

INSERT INTO ORDERS (CREATION_DATE, CUSTOMER_ID, PRODUCT_ID) VALUES ('2020-09-09', 1, 1)
INSERT INTO ORDERS (CREATION_DATE, CUSTOMER_ID, PRODUCT_ID) VALUES ('2020-09-10', 1, 2)
INSERT INTO ORDERS (CREATION_DATE, CUSTOMER_ID, PRODUCT_ID) VALUES ('2020-09-09', 2, 2)
